server:
  port: ${PORT:8080}

spring:
  application:
    name: eventify
  datasource:
    url: "jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:eventify}?sslmode=${PGSSLMODE:require}&gssEncMode=disable&sslNegotiation=direct"
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        auto_quote_keyword: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  sql:
    init:
      mode: always
      platform: postgresql

jwt:
  secret: ${JWT_SECRET:your-secret-key-must-be-at-least-256-bits-long-for-HS256-algorithm}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:8080
    - https://eventify-front-end.onrender.com
  allowed-origin-patterns:
    - https://*.onrender.com
    - https://*.vercel.app
