-- =========================
-- Cities
-- =========================
INSERT INTO cities (name, region, country) VALUES
    ('Brussels', 'Brussels-Capital Region', 'Belgium'),
    ('Antwerp', 'Flanders', 'Belgium'),
    ('Ghent', 'Flanders', 'Belgium'),
    ('Bruges', 'Flanders', 'Belgium'),
    ('Liège', 'Wallonia', 'Belgium')
ON CONFLICT DO NOTHING;

-- =========================
-- Venues
-- =========================
INSERT INTO venues (name, address, capacity, city_id) SELECT 'Forest National', 'Avenue du Globe 36, 1190 Forest', 8000, city_id FROM cities WHERE name = 'Brussels' AND NOT EXISTS (SELECT 1 FROM venues WHERE name = 'Forest National');
INSERT INTO venues (name, address, capacity, city_id) SELECT 'Palais 12', 'Avenue de Marathon 1, 1020 Laeken', 12000, city_id FROM cities WHERE name = 'Brussels' AND NOT EXISTS (SELECT 1 FROM venues WHERE name = 'Palais 12');
INSERT INTO venues (name, address, capacity, city_id) SELECT 'Ancienne Belgique', 'Boulevard Anspach 110, 1000 Brussels', 2000, city_id FROM cities WHERE name = 'Brussels' AND NOT EXISTS (SELECT 1 FROM venues WHERE name = 'Ancienne Belgique');
INSERT INTO venues (name, address, capacity, city_id) SELECT 'Lotto Arena', 'Sportpaleis­laan 1, 2020 Antwerp', 8000, city_id FROM cities WHERE name = 'Antwerp' AND NOT EXISTS (SELECT 1 FROM venues WHERE name = 'Lotto Arena');
INSERT INTO venues (name, address, capacity, city_id) SELECT 'Sportpaleis', 'Sportpaleis­laan 1, 2020 Antwerp', 23000, city_id FROM cities WHERE name = 'Antwerp' AND NOT EXISTS (SELECT 1 FROM venues WHERE name = 'Sportpaleis');
INSERT INTO venues (name, address, capacity, city_id) SELECT 'Trix', 'Noordersingel 28, 2140 Antwerp', 1400, city_id FROM cities WHERE name = 'Antwerp' AND NOT EXISTS (SELECT 1 FROM venues WHERE name = 'Trix');
INSERT INTO venues (name, address, capacity, city_id) SELECT 'Vooruit', 'Sint-Pietersnieuwstraat 23, 9000 Ghent', 1700, city_id FROM cities WHERE name = 'Ghent' AND NOT EXISTS (SELECT 1 FROM venues WHERE name = 'Vooruit');
INSERT INTO venues (name, address, capacity, city_id) SELECT 'Capitole Ghent', 'Graaf van Vlaanderenplein 29, 9000 Ghent', 2000, city_id FROM cities WHERE name = 'Ghent' AND NOT EXISTS (SELECT 1 FROM venues WHERE name = 'Capitole Ghent');
INSERT INTO venues (name, address, capacity, city_id) SELECT 'Cactus Club', 'Magdalenastraat 27, 8000 Bruges', 500, city_id FROM cities WHERE name = 'Bruges' AND NOT EXISTS (SELECT 1 FROM venues WHERE name = 'Cactus Club');
INSERT INTO venues (name, address, capacity, city_id) SELECT 'La Boverie', 'Parc de la Boverie, 4020 Liège', 3000, city_id FROM cities WHERE name = 'Liège' AND NOT EXISTS (SELECT 1 FROM venues WHERE name = 'La Boverie');

-- =========================
-- Events
-- =========================
INSERT INTO events (title, event_date, start_time, end_time, available_tickets) SELECT 'Stromae Live 2026', '2026-03-15', '20:00', '23:00', 8000 WHERE NOT EXISTS (SELECT 1 FROM events WHERE title = 'Stromae Live 2026');
INSERT INTO events (title, event_date, start_time, end_time, available_tickets) SELECT 'Dua Lipa – Radical Optimism Tour', '2026-04-02', '19:30', '22:30', 12000 WHERE NOT EXISTS (SELECT 1 FROM events WHERE title = 'Dua Lipa – Radical Optimism Tour');
INSERT INTO events (title, event_date, start_time, end_time, available_tickets) SELECT 'Jazz Middelheim Preview Night', '2026-04-18', '18:00', '23:00', 1800 WHERE NOT EXISTS (SELECT 1 FROM events WHERE title = 'Jazz Middelheim Preview Night');
INSERT INTO events (title, event_date, start_time, end_time, available_tickets) SELECT 'Rammstein European Tour', '2026-05-10', '19:00', '22:30', 22000 WHERE NOT EXISTS (SELECT 1 FROM events WHERE title = 'Rammstein European Tour');
INSERT INTO events (title, event_date, start_time, end_time, available_tickets) SELECT 'Tomorrowland Winter Warm-Up', '2026-05-24', '14:00', '23:59', 7500 WHERE NOT EXISTS (SELECT 1 FROM events WHERE title = 'Tomorrowland Winter Warm-Up');
INSERT INTO events (title, event_date, start_time, end_time, available_tickets) SELECT 'Arctic Monkeys', '2026-06-06', '20:00', '23:00', 7800 WHERE NOT EXISTS (SELECT 1 FROM events WHERE title = 'Arctic Monkeys');
INSERT INTO events (title, event_date, start_time, end_time, available_tickets) SELECT 'Rock Werchter Opening Night', '2026-07-02', '16:00', '23:59', 12000 WHERE NOT EXISTS (SELECT 1 FROM events WHERE title = 'Rock Werchter Opening Night');
INSERT INTO events (title, event_date, start_time, end_time, available_tickets) SELECT 'Editors – EBM Night', '2026-07-19', '20:30', '23:30', 1600 WHERE NOT EXISTS (SELECT 1 FROM events WHERE title = 'Editors – EBM Night');
INSERT INTO events (title, event_date, start_time, end_time, available_tickets) SELECT 'Balthazar Farewell Show', '2026-08-08', '20:00', '23:00', 1900 WHERE NOT EXISTS (SELECT 1 FROM events WHERE title = 'Balthazar Farewell Show');
INSERT INTO events (title, event_date, start_time, end_time, available_tickets) SELECT 'Coldplay – Music of the Spheres', '2026-08-22', '19:00', '23:00', 23000 WHERE NOT EXISTS (SELECT 1 FROM events WHERE title = 'Coldplay – Music of the Spheres');
INSERT INTO events (title, event_date, start_time, end_time, available_tickets) SELECT 'Massive Attack', '2026-09-05', '21:00', '23:30', 2000 WHERE NOT EXISTS (SELECT 1 FROM events WHERE title = 'Massive Attack');
INSERT INTO events (title, event_date, start_time, end_time, available_tickets) SELECT 'Ghent Jazz Festival Closing', '2026-09-13', '15:00', '23:00', 3000 WHERE NOT EXISTS (SELECT 1 FROM events WHERE title = 'Ghent Jazz Festival Closing');
INSERT INTO events (title, event_date, start_time, end_time, available_tickets) SELECT 'Amenra – Church of Ra', '2026-10-03', '20:00', '23:00', 480 WHERE NOT EXISTS (SELECT 1 FROM events WHERE title = 'Amenra – Church of Ra');
INSERT INTO events (title, event_date, start_time, end_time, available_tickets) SELECT 'Brussels Electronic Marathon', '2026-10-17', '22:00', '23:59', 1200 WHERE NOT EXISTS (SELECT 1 FROM events WHERE title = 'Brussels Electronic Marathon');
INSERT INTO events (title, event_date, start_time, end_time, available_tickets) SELECT 'Liège Philharmonic Gala', '2026-11-28', '19:30', '22:00', 1500 WHERE NOT EXISTS (SELECT 1 FROM events WHERE title = 'Liège Philharmonic Gala');

-- =========================
-- Event Descriptions (lookup event_id by title)
-- =========================
INSERT INTO event_descriptions (event_id, event_type, featured_artists, ticket_purchase_link, extra_description) SELECT e.event_id, 'Concert', 'Stromae', 'https://tickets.forestnational.be', 'Stromae returns to Belgium for a spectacular homecoming show.' FROM events e WHERE e.title = 'Stromae Live 2026' AND NOT EXISTS (SELECT 1 FROM event_descriptions WHERE event_id = e.event_id);
INSERT INTO event_descriptions (event_id, event_type, featured_artists, ticket_purchase_link, extra_description) SELECT e.event_id, 'Concert', 'Dua Lipa', 'https://tickets.palais12.be', 'Pop sensation Dua Lipa brings her Radical Optimism Tour to Brussels.' FROM events e WHERE e.title = 'Dua Lipa – Radical Optimism Tour' AND NOT EXISTS (SELECT 1 FROM event_descriptions WHERE event_id = e.event_id);
INSERT INTO event_descriptions (event_id, event_type, featured_artists, ticket_purchase_link, extra_description) SELECT e.event_id, 'Jazz', 'Various Jazz Artists', 'https://jazzmiddelheim.be', 'A preview evening ahead of the main Jazz Middelheim festival.' FROM events e WHERE e.title = 'Jazz Middelheim Preview Night' AND NOT EXISTS (SELECT 1 FROM event_descriptions WHERE event_id = e.event_id);
INSERT INTO event_descriptions (event_id, event_type, featured_artists, ticket_purchase_link, extra_description) SELECT e.event_id, 'Rock', 'Rammstein', 'https://tickets.sportpaleis.be', 'German industrial metal giants Rammstein with their legendary pyrotechnics.' FROM events e WHERE e.title = 'Rammstein European Tour' AND NOT EXISTS (SELECT 1 FROM event_descriptions WHERE event_id = e.event_id);
INSERT INTO event_descriptions (event_id, event_type, featured_artists, ticket_purchase_link, extra_description) SELECT e.event_id, 'Electronic', 'Various DJs', 'https://tomorrowland.com', 'Official Tomorrowland warm-up party at Lotto Arena.' FROM events e WHERE e.title = 'Tomorrowland Winter Warm-Up' AND NOT EXISTS (SELECT 1 FROM event_descriptions WHERE event_id = e.event_id);
INSERT INTO event_descriptions (event_id, event_type, featured_artists, ticket_purchase_link, extra_description) SELECT e.event_id, 'Rock', 'Arctic Monkeys', 'https://tickets.forestnational.be', 'Sheffield indie rock legends Arctic Monkeys on their world tour.' FROM events e WHERE e.title = 'Arctic Monkeys' AND NOT EXISTS (SELECT 1 FROM event_descriptions WHERE event_id = e.event_id);
INSERT INTO event_descriptions (event_id, event_type, featured_artists, ticket_purchase_link, extra_description) SELECT e.event_id, 'Festival', 'Various Artists', 'https://rockwerchter.be', 'Opening night of Rock Werchter with a star-studded lineup.' FROM events e WHERE e.title = 'Rock Werchter Opening Night' AND NOT EXISTS (SELECT 1 FROM event_descriptions WHERE event_id = e.event_id);
INSERT INTO event_descriptions (event_id, event_type, featured_artists, ticket_purchase_link, extra_description) SELECT e.event_id, 'Alternative', 'Editors', 'https://tickets.vooruit.be', 'Post-punk legends Editors with a special EBM-influenced set.' FROM events e WHERE e.title = 'Editors – EBM Night' AND NOT EXISTS (SELECT 1 FROM event_descriptions WHERE event_id = e.event_id);
INSERT INTO event_descriptions (event_id, event_type, featured_artists, ticket_purchase_link, extra_description) SELECT e.event_id, 'Indie', 'Balthazar', 'https://tickets.capitoleghent.be', 'Ghent''s own Balthazar in an emotional farewell show at home.' FROM events e WHERE e.title = 'Balthazar Farewell Show' AND NOT EXISTS (SELECT 1 FROM event_descriptions WHERE event_id = e.event_id);
INSERT INTO event_descriptions (event_id, event_type, featured_artists, ticket_purchase_link, extra_description) SELECT e.event_id, 'Concert', 'Coldplay', 'https://tickets.sportpaleis.be', 'Coldplay''s eco-friendly spectacular with their Music of the Spheres show.' FROM events e WHERE e.title = 'Coldplay – Music of the Spheres' AND NOT EXISTS (SELECT 1 FROM event_descriptions WHERE event_id = e.event_id);
INSERT INTO event_descriptions (event_id, event_type, featured_artists, ticket_purchase_link, extra_description) SELECT e.event_id, 'Electronic', 'Massive Attack', 'https://tickets.ab.be', 'Trip-hop pioneers Massive Attack with a visually stunning audio-visual experience.' FROM events e WHERE e.title = 'Massive Attack' AND NOT EXISTS (SELECT 1 FROM event_descriptions WHERE event_id = e.event_id);
INSERT INTO event_descriptions (event_id, event_type, featured_artists, ticket_purchase_link, extra_description) SELECT e.event_id, 'Jazz', 'Various Jazz Artists', 'https://gentjazz.com', 'Closing night of the Ghent Jazz Festival with special guests.' FROM events e WHERE e.title = 'Ghent Jazz Festival Closing' AND NOT EXISTS (SELECT 1 FROM event_descriptions WHERE event_id = e.event_id);
INSERT INTO event_descriptions (event_id, event_type, featured_artists, ticket_purchase_link, extra_description) SELECT e.event_id, 'Metal', 'Amenra', 'https://tickets.cactusmuziekcentrum.be', 'Intimate Church of Ra show — Amenra at their most raw and powerful.' FROM events e WHERE e.title = 'Amenra – Church of Ra' AND NOT EXISTS (SELECT 1 FROM event_descriptions WHERE event_id = e.event_id);
INSERT INTO event_descriptions (event_id, event_type, featured_artists, ticket_purchase_link, extra_description) SELECT e.event_id, 'Electronic', 'Various DJs', 'https://tickets.ab.be', 'An all-night electronic marathon across multiple stages in Brussels.' FROM events e WHERE e.title = 'Brussels Electronic Marathon' AND NOT EXISTS (SELECT 1 FROM event_descriptions WHERE event_id = e.event_id);
INSERT INTO event_descriptions (event_id, event_type, featured_artists, ticket_purchase_link, extra_description) SELECT e.event_id, 'Classical', 'Liège Philharmonic Orchestra', 'https://oprl.be', 'A grand classical gala evening with the Liège Philharmonic Orchestra.' FROM events e WHERE e.title = 'Liège Philharmonic Gala' AND NOT EXISTS (SELECT 1 FROM event_descriptions WHERE event_id = e.event_id);

-- =========================
-- Event ↔ Venue links (lookup IDs by name)
-- =========================
INSERT INTO event_venues (event_id, venue_id) SELECT e.event_id, v.venue_id FROM events e, venues v WHERE e.title = 'Stromae Live 2026' AND v.name = 'Forest National' AND NOT EXISTS (SELECT 1 FROM event_venues WHERE event_id = e.event_id AND venue_id = v.venue_id);
INSERT INTO event_venues (event_id, venue_id) SELECT e.event_id, v.venue_id FROM events e, venues v WHERE e.title = 'Dua Lipa – Radical Optimism Tour' AND v.name = 'Palais 12' AND NOT EXISTS (SELECT 1 FROM event_venues WHERE event_id = e.event_id AND venue_id = v.venue_id);
INSERT INTO event_venues (event_id, venue_id) SELECT e.event_id, v.venue_id FROM events e, venues v WHERE e.title = 'Jazz Middelheim Preview Night' AND v.name = 'Trix' AND NOT EXISTS (SELECT 1 FROM event_venues WHERE event_id = e.event_id AND venue_id = v.venue_id);
INSERT INTO event_venues (event_id, venue_id) SELECT e.event_id, v.venue_id FROM events e, venues v WHERE e.title = 'Rammstein European Tour' AND v.name = 'Sportpaleis' AND NOT EXISTS (SELECT 1 FROM event_venues WHERE event_id = e.event_id AND venue_id = v.venue_id);
INSERT INTO event_venues (event_id, venue_id) SELECT e.event_id, v.venue_id FROM events e, venues v WHERE e.title = 'Tomorrowland Winter Warm-Up' AND v.name = 'Lotto Arena' AND NOT EXISTS (SELECT 1 FROM event_venues WHERE event_id = e.event_id AND venue_id = v.venue_id);
INSERT INTO event_venues (event_id, venue_id) SELECT e.event_id, v.venue_id FROM events e, venues v WHERE e.title = 'Arctic Monkeys' AND v.name = 'Forest National' AND NOT EXISTS (SELECT 1 FROM event_venues WHERE event_id = e.event_id AND venue_id = v.venue_id);
INSERT INTO event_venues (event_id, venue_id) SELECT e.event_id, v.venue_id FROM events e, venues v WHERE e.title = 'Rock Werchter Opening Night' AND v.name = 'Palais 12' AND NOT EXISTS (SELECT 1 FROM event_venues WHERE event_id = e.event_id AND venue_id = v.venue_id);
INSERT INTO event_venues (event_id, venue_id) SELECT e.event_id, v.venue_id FROM events e, venues v WHERE e.title = 'Editors – EBM Night' AND v.name = 'Vooruit' AND NOT EXISTS (SELECT 1 FROM event_venues WHERE event_id = e.event_id AND venue_id = v.venue_id);
INSERT INTO event_venues (event_id, venue_id) SELECT e.event_id, v.venue_id FROM events e, venues v WHERE e.title = 'Balthazar Farewell Show' AND v.name = 'Capitole Ghent' AND NOT EXISTS (SELECT 1 FROM event_venues WHERE event_id = e.event_id AND venue_id = v.venue_id);
INSERT INTO event_venues (event_id, venue_id) SELECT e.event_id, v.venue_id FROM events e, venues v WHERE e.title = 'Coldplay – Music of the Spheres' AND v.name = 'Sportpaleis' AND NOT EXISTS (SELECT 1 FROM event_venues WHERE event_id = e.event_id AND venue_id = v.venue_id);
INSERT INTO event_venues (event_id, venue_id) SELECT e.event_id, v.venue_id FROM events e, venues v WHERE e.title = 'Massive Attack' AND v.name = 'Ancienne Belgique' AND NOT EXISTS (SELECT 1 FROM event_venues WHERE event_id = e.event_id AND venue_id = v.venue_id);
INSERT INTO event_venues (event_id, venue_id) SELECT e.event_id, v.venue_id FROM events e, venues v WHERE e.title = 'Ghent Jazz Festival Closing' AND v.name = 'Vooruit' AND NOT EXISTS (SELECT 1 FROM event_venues WHERE event_id = e.event_id AND venue_id = v.venue_id);
INSERT INTO event_venues (event_id, venue_id) SELECT e.event_id, v.venue_id FROM events e, venues v WHERE e.title = 'Amenra – Church of Ra' AND v.name = 'Cactus Club' AND NOT EXISTS (SELECT 1 FROM event_venues WHERE event_id = e.event_id AND venue_id = v.venue_id);
INSERT INTO event_venues (event_id, venue_id) SELECT e.event_id, v.venue_id FROM events e, venues v WHERE e.title = 'Brussels Electronic Marathon' AND v.name = 'Ancienne Belgique' AND NOT EXISTS (SELECT 1 FROM event_venues WHERE event_id = e.event_id AND venue_id = v.venue_id);
INSERT INTO event_venues (event_id, venue_id) SELECT e.event_id, v.venue_id FROM events e, venues v WHERE e.title = 'Liège Philharmonic Gala' AND v.name = 'La Boverie' AND NOT EXISTS (SELECT 1 FROM event_venues WHERE event_id = e.event_id AND venue_id = v.venue_id);
